import { useState, useMemo } from 'react'
import { ScrollView, View, Text, TextInput, TouchableOpacity, StyleSheet, Share } from 'react-native'
import * as Print from 'expo-print'
import { Ionicons } from '@expo/vector-icons'
import { calcPCB, fmt, fmtI } from '../../shared/calculators'
import { C, s, SP, R, W, shadow, shadowMd } from '../../src/theme/index'

export default function PCBScreen() {
  const [salary, setSalary] = useState('')
  const [calculated, setCalculated] = useState(false)

  const r = useMemo(() => calcPCB(parseFloat(salary) || 0), [salary])
  const canCalc = parseFloat(salary) > 0

  const exportPDF = async () => {
    const html = `<html><body style="font-family:-apple-system,sans-serif;padding:24px;">
      <h2>PCB Tax Calculator — NikiBhavi</h2>
      <p>Monthly Gross: RM ${r.gross.toLocaleString()}</p>
      <table style="width:100%;border-collapse:collapse;font-size:14px;">
        <tr style="background:#E6F7EE;"><th style="padding:10px;text-align:left;">Item</th><th style="text-align:right;padding:10px;">Amount</th></tr>
        <tr><td style="padding:8px 10px;">EPF (11%)</td><td style="text-align:right;">RM ${r.epf.toLocaleString()}</td></tr>
        <tr><td style="padding:8px 10px;">SOCSO</td><td style="text-align:right;">RM ${r.socso.toLocaleString()}</td></tr>
        <tr><td style="padding:8px 10px;">EIS</td><td style="text-align:right;">RM ${r.eis.toLocaleString()}</td></tr>
        <tr><td style="padding:8px 10px;">PCB / Income Tax</td><td style="text-align:right;">RM ${r.pcb.toLocaleString()}</td></tr>
        <tr style="background:#E6F7EE;font-weight:700;"><td style="padding:10px;">Take-Home Pay</td><td style="text-align:right;color:#00B14F;">RM ${r.takehome.toLocaleString()}</td></tr>
      </table>
      <p style="font-size:11px;color:#999;margin-top:16px;">Generated by NikiBhavi • nikibhavi.msdevbuild.com</p>
    </body></html>`
    try {
      const { uri } = await Print.printToFileAsync({ html })
      await Share.share({ url: uri, title: 'PCB Tax Report' })
    } catch { await Print.printAsync({ html }) }
  }

  return (
    <ScrollView style={s.screen} showsVerticalScrollIndicator={false} keyboardShouldPersistTaps="handled"
      contentContainerStyle={{ paddingBottom: 40 }}>

      <Text style={s.sectionHdr}>Your Monthly Salary</Text>
      <View style={s.inputGroup}>
        <View style={[s.inputRow, { borderBottomWidth:0 }]}>
          <Text style={s.inputLabel}>Gross Salary</Text>
          <Text style={[s.small, { marginRight:6, color:C.muted }]}>RM</Text>
          <TextInput style={s.input} value={salary} onChangeText={t => { setSalary(t); setCalculated(false) }}
            keyboardType="numeric" placeholder="e.g. 8000"
            placeholderTextColor={C.placeholder} returnKeyType="done" />
        </View>
      </View>

      <TouchableOpacity style={[s.btnPrimary, !canCalc && { opacity:0.45 }]}
        onPress={() => canCalc && setCalculated(true)} activeOpacity={0.8}>
        <Text style={s.btnText}>Calculate PCB</Text>
      </TouchableOpacity>

      {calculated && canCalc && (
        <>
          <View style={[ls.resultCard, { backgroundColor: C.primary }]}>
            <Text style={s.resultLabel}>Monthly Take-Home Pay</Text>
            <Text style={s.resultValue}>{fmt(r.takehome)}</Text>
            <Text style={s.resultSub}>{fmtI(r.takehome)}/mo · Annual: {fmt(r.takehome * 12)}</Text>
          </View>

          <Text style={s.sectionHdr}>Monthly Deductions</Text>
          <View style={s.card}>
            {[
              { label:'EPF (11%)',        value:fmt(r.epf),   color:C.info,   pct:r.epf/r.gross   },
              { label:'SOCSO',            value:fmt(r.socso), color:C.orange, pct:r.socso/r.gross },
              { label:'EIS',              value:fmt(r.eis),   color:C.purple, pct:r.eis/r.gross   },
              { label:'PCB (Income Tax)', value:fmt(r.pcb),   color:C.danger, pct:r.pcb/r.gross   },
            ].map((row, i, arr) => (
              <View key={row.label} style={i < arr.length-1 ? s.row : s.rowLast}>
                <View style={{ flex:1 }}>
                  <Text style={s.title}>{row.label}</Text>
                  <View style={ls.barBg}>
                    <View style={[ls.barFill, { width:`${Math.min(100,(row.pct||0)*100)}%`, backgroundColor:row.color }]} />
                  </View>
                </View>
                <Text style={[s.title, { color:row.color, marginLeft:12, fontWeight:W.bold }]}>{row.value}</Text>
              </View>
            ))}
          </View>

          <Text style={s.sectionHdr}>Summary</Text>
          <View style={s.card}>
            {[
              ['Gross Salary',        fmt(r.gross),                 C.label  ],
              ['Total Deductions',    `− ${fmt(r.totalDeductions)}`, C.danger ],
              ['Take-Home Pay',       fmt(r.takehome),              C.primary],
              ['Annual Tax (PCB×12)', fmt(r.annualTax),             C.orange ],
              ['Take-Home (INR)',     fmtI(r.takehome),             C.info   ],
            ].map(([l,v,c], i, arr) => (
              <View key={l} style={i < arr.length-1 ? s.row : s.rowLast}>
                <Text style={[s.body, { flex:1 }]}>{l}</Text>
                <Text style={[s.title, { color:c, fontWeight: i===2 ? W.bold : W.semibold }]}>{v}</Text>
              </View>
            ))}
          </View>

          <TouchableOpacity style={[s.btnSecondary, { marginTop:SP.sm }]} onPress={exportPDF} activeOpacity={0.8}>
            <Text style={s.btnTextSec}>📄  Export PDF Report</Text>
          </TouchableOpacity>
        </>
      )}
    </ScrollView>
  )
}

const ls = StyleSheet.create({
  resultCard: { marginHorizontal:SP.lg, marginTop:SP.lg, borderRadius:R.xxl, padding:SP.xl, ...shadowMd },
  barBg:      { height:4, backgroundColor:'#EEE', borderRadius:2, marginTop:4, overflow:'hidden' },
  barFill:    { height:4, borderRadius:2 },
})
